### ISSUE TITLE
should mention somewhere that the project doesn't run on its own

### ISSUE THREAD

**Issue by SwingsetTheory** [roubachof/Xamarin-Forms-Practices#7]
I had to do a bunch of fiddling to get it working.

Ultimately I had to download the whole Sharpnado.Presentation.Forms project and manually drag it into this project in visual studio before this would run.

There may be a smarter way, but I obviously didn't think of it, and there's no information about it anywhere.

**Comment by jfversluis** [comment]
Yep, I just came across this as well. Probably because of the submodule being used.

Personally I would just make this project use the NuGet package and lose the submodule which makes it much easier for people to run this out of the box. Since you will have the update the submodule reference just like you would update a NuGet package, I feel for the end-user a NuGet package would be much easier and for the effort you have to put into it would be the same.

**Comment by roubachof** [comment]
added the glorious "important" section:
https://github.com/roubachof/Xamarin-Forms-Practices#important
